# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=345, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cropping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=400)),
                ('area', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Datetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('wateryield', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('sequeneno', models.IntegerField()),
                ('season', models.CharField(max_length=345, unique=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Farmphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=400)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('income', models.FloatField()),
                ('doorno', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Houseaudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=400)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.House')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.House')),
            ],
        ),
        migrations.CreateModel(
            name='Housephoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=400)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.House')),
            ],
        ),
        migrations.CreateModel(
            name='Housevideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=400)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.House')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('depth', models.FloatField()),
                ('averageWaterYield', models.FloatField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Wellphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=350)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Well')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='farm',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.House'),
        ),
        migrations.AddField(
            model_name='datetime',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Well'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Farm'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Season'),
        ),
    ]
