# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20170917_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housephoto',
            name='photo',
            field=models.FileField(max_length=400, upload_to=b''),
        ),
    ]
