# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20171004_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housephoto',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
