# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20171006_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropping',
            name='season',
            field=models.CharField(max_length=345),
        ),
    ]
