# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20171006_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropping',
            old_name='nutspercent',
            new_name='oilseedspercent',
        ),
        migrations.RemoveField(
            model_name='cropping',
            name='sunflowerpercent',
        ),
    ]
